# Generated by Django 4.1.7 on 2023-06-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=120)),
                ('edept', models.CharField(max_length=120)),
                ('esal', models.IntegerField()),
            ],
        ),
    ]
